# Generated by Django 4.0.3 on 2022-04-14 18:21

import Exam_Django.store.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default=Exam_Django.store.models.create_new_ref_number, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('av_qnt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.CharField(default='No brand', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women'), ('KIDS', 'kids')], max_length=5)),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SHIRTS', 'shirts'), ('JEANS', 'Jeans'), ('TOPS', 'Tops'), ('JACKETS', 'Jackets'), ('COATS', 'Coats'), ('SHOES', 'Shoes')], max_length=7)),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.product')),
            ],
        ),
    ]
